package com.remoterecorder.agent.model

enum class ErrorCode {
    MIC_PERMISSION_DENIED,
    MICROPHONE_UNAVAILABLE,
    ENCODER_UNAVAILABLE,
    UNSUPPORTED_CONFIGURATION,
    STORAGE_ERROR,
    NETWORK_ERROR,
    WEBSOCKET_ERROR,
    UPLOAD_ERROR,
    FINALIZATION_ERROR,
    SERVICE_ERROR,
}
